---
# Edit the following variables as necessary according to your environment

#vCenter specific variables (For Tower/AWX, vCenter Inventory is used.)
vcenter_hostname: '{{ lookup("env", "VMWARE_HOST") }}'
vcenter_username: '{{ lookup("env", "VMWARE_USER") }}'
vcenter_password: '{{ lookup("env", "VMWARE_PASSWORD") }}'

# ONTAP Cluster to integrate (For Tower/AWX, ONTAP Inventory is used.)
netapp_hostname: '{{ lookup("env", "ONTAP_CLUSTERFQDN") }}'


#Path to OVF or OVA file to deploy.
ova_path: netapp-ontap-tools-for-vmware-vsphere-9.8-7032.ova

#Name of the VM to work with
vm_name: netapp-ontap-tools-wld01

#Datacenter to deploy to
datacenter: RTP

#Cluster to deploy to
cluster: Tanzu

#Datastore to deploy to
datastore: NFS-02

#Portgroup for ONTAP tools Appliance.
portgroup: Management


#Application User Password. For Tower/AWX, used custom credential type 
app_user_passwd: '{{ netapp_password }}'

#Maintenance User Password. For Tower/AWX, used custom credential type
maint_user_passwd: '{{ netapp_password }}'

#Specify the hostname for the appliance
ontap_tools_hostname: netapp-ontap-tools-wld01

#IP address for the appliance
ontap_tools_ip: "X.X.X.X"

#Subnet to use on the deployed network
ontap_tools_netmask: "255.255.255.0"

#Gateway on the deployed network
ontap_tools_gateway: "X.X.X.Y"

#NTP Server
ntp_server: time.netapp.com

#DNS Server
dns_server: "A.B.C.D, A.B.C.E"

#DNS Domain Name
dns_domain: 

#Default datastore type to query and remove.
datastore_type: VMFS