--- 
- name: ONTAP Storage Re-Discover
  uri:
    url: "https://{{ ontap_tools_ip }}:8143/api/rest/2.0/storage/clusters/discover" 
    validate_certs: false
    method: POST
    return_content: yes
    body_format: json
    headers:
      vmware-api-session-id: "{{ ontap_vc_session_id }}"
